name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  EXTNAME: SemanticReports
  MW_INSTALL_PATH: ${{ github.workspace }}

jobs:
  style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: wikiteq/php-lint-action@main

  security:
    name: Static Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mediawiki: REL1_39
            smw: 4.2.0
          - mediawiki: REL1_43
            smw: 5.0.2
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: '8.1'
          extensions: mbstring, intl, ast
          coverage: none
          tools: composer
      - name: Setup MediaWiki
        uses: actions/checkout@v4
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mediawiki }}
      - name: Setup dependency - SemanticMediaWiki
        uses: actions/checkout@v4
        with:
          path: extensions/SemanticMediaWiki
          ref: ${{ matrix.smw }}
          repository: SemanticMediaWiki/SemanticMediaWiki
      - name: Setup Extension
        uses: actions/checkout@v4
        with:
          path: extensions/${{ env.EXTNAME }}
      - name: Setup Composer
        run: |
          echo '{"extra":{"merge-plugin":{"include":["extensions/*/composer.json","skins/*/composer.json"]}}}' > composer.local.json
          composer update
          composer update
          composer config repositories.wikiteq/phan-mediawikiservices-check-plugin git https://github.com/WikiTeq/phan-mediawikiservices-check-plugin.git
          composer require "wikiteq/phan-mediawikiservices-check-plugin:v0.2.0"
      - name: Phan
        run: ./vendor/bin/phan -d extensions/${{ env.EXTNAME }} --minimum-target-php-version=8.1 --long-progress-bar

  i18n-check:
    name: I18n check
    runs-on: ubuntu-latest
    steps:
      - name: I18n check action
        uses: wikiteq/mediawiki-i18n-check-action@main
        with:
          extension: EncryptedContent

# enable once we have tests
#  test:
#    name: PHPUnit
#    runs-on: ubuntu-latest
#    env:
#      MW_INSTALL_PATH: ${{ github.workspace }}/mediawiki
#    strategy:
#      fail-fast: false
#      matrix:
#        php: [ '8.1' ]
#        mediawiki: [ REL1_39, REL1_43 ]
#    steps:
#      - name: Setup Extension
#        uses: actions/checkout@v4
#      - name: Setup dependency - AbuseFilter
#        uses: actions/checkout@v4
#        with:
#          path: ${{ github.workspace }}/AbuseFilter
#          ref: REL1_43
#          repository: wikimedia/mediawiki-extensions-AbuseFilter
#      - name: Mediawiki PHPUnit
#        uses: wikiteq/mediawiki-phpunit-action@master
#        with:
#          type: extension
#          php: ${{ matrix.php }}
#          mwbranch: ${{ matrix.mediawiki }}
#          extension: EncryptedContent
#          extra_file: .github/PHPUnitSettings.php
